### ISSUE TITLE
rationale for moving away from pkg-config?

### ISSUE THREAD

**Issue by cmyr** [fullcontact/icu-sys#1]
hi there,

I'm currently looking at using icu in a rust project and I'm assaying my options. I'm curious about the decision to forgo using a system `libicu` where available. Were there issues you encountered there? If so I'd really appreciate the chance to avoid making them myself.

thanks!

**Comment by AltSysrq** [comment]
The main issue is the symbol renaming ICU does. If you do `objdump -T` on one of the ICU libraries installed on your system, you'll likely find that every public symbol has the version, eg `_57`, appended to it. This is done _in the C preprocessor_ to make it transparent to C/C++ programs. But from Rust, this of course does not happen, so the Rust linkage would need to use the renamed symbol. Unfortunately, this would mean that the resulting crate would work _only with that one version of ICU_, which largely undermines the benefit of using whatever happens to be on the system already.

What we do here is [build ICU with `-DU_DISABLE_RENAMING=1` defined](https://github.com/fullcontact/icu-sys/commit/d1ff44ec5c398bba6755bf6880c4284e0ef63735#diff-aeb062d5da0fd6d93d6bc41107264d7bR11), which disables this renaming so that the ICU version can be upgraded easily without needing to reimplement our own symbol renaming.

**Comment by cmyr** [comment]
Yea okay, interesting. Thanks for the explanation!
